### ISSUE TITLE
Windows/MacOS version

### ISSUE THREAD

**Issue by MarcAnt01** [open-polito/open-polito#109]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have a native version for Windows and MacOS. The polito website has some problems with the adaptive UI and lacks push notifications

**Describe the solution you'd like**
Windows and MacOS release using https://microsoft.github.io/react-native-windows/

**Describe the benefits of said feature**
Include desktop platform

**Optional: Describe alternatives you've considered**
None

**Comment by robertolaru** [comment]
Hi, thanks for the suggestion!
I agree it would be very useful to have the app built as a desktop app. `react-native-windows` does seem promising, though it lacks Linux support.
I'd definitely add desktop support in a next app milestone, after planned features get implemented. Either with `react-native-windows` or something else if we want to support Linux as well.

**Comment by robertolaru** [comment]
@MarcAnt01 I recently implemented desktop support for Linux, Windows & MacOS with Tauri, right now on a separate branch but will be soon merged to master and a new release will be published.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 I recently implemented desktop support for Linux, Windows & MacOS with Tauri, right now on a separate branch but will be soon merged to master and a new release will be published.

According to what I've understood Tauri is an Electron-like framework. To me it's not comparable at all to a native desktop framework like React Native and it kinda defeats the point of having the app ported to Desktop, when I can use the polito site instead
