### ISSUE TITLE
Jump to date's popup cancel button has wrong behavior 

### ISSUE THREAD

**Issue by ilovelinux** [open-polito/open-polito#115]
**Describe the bug**
On timetable there's a button that opens a calendar popup to jump to a specific date, but when you click on "cancel" button, it will jump to today's date instead of do nothing.

**To Reproduce**
1. Go to 'Timetable'
2. Click on 'Jump to date'
3. Choose a random date in the future or in the past (at least 1 week before/after the day's date) and confirm
4. Click again on 'Jump to date'
5. Click on 'Cancel'

**Expected behavior**
Date shouldn't be changed.

**Comment by robertolaru** [comment]
This seems to have been fixed by downgrading `@react-native-community/datetimepicker` in c4b79b5c8cd1f
