### ISSUE TITLE
Hard to scroll through courses in the materials page if the course names are long

### ISSUE THREAD

**Issue by CapacitorSet** [open-polito/open-polito#19]
Title. If many course names are long (eg. "System and device programming", "Data science and database technology", "Architetture dei sistemi di elaborazione), it takes a lot of scrolling to browse to different courses in the materials page. Perhaps the UI should feature a vertical list of courses somehow.

**Comment by robertolaru** [comment]
Will use a vertical popup selector to make scrolling easier. Same selector will also be used for feature #21 (Add an option to limit search to a specific course)
