### ISSUE TITLE
Properly align icons and texts in the course view.

### ISSUE THREAD

**Issue by xNicklaj** [open-polito/open-polito#30]
Sometimes icons and text appear misaligned or in multiple rows.
![Screenshot_20211220-151454.jpg](https://user-images.githubusercontent.com/40305701/146780758-fbbd2c26-5aee-40fd-84b0-471dc660746e.jpg)

**Comment by robertolaru** [comment]
This is due to the excessive amount of tabs, which will be reduced to the most important tabs, leaving the remaining sections accessible from the Overview tab itself

**Comment by robertolaru** [comment]
This is now solved with commit d89d0e7, as there are only 4 tabs.
