### ISSUE TITLE
Material: show dates as "X days ago" rather than date/time

### ISSUE THREAD

**Issue by CapacitorSet** [open-polito/open-polito#8]

**Comment by robertolaru** [comment]
This has now been implemented in commit 4cd8842a9e4e7dc7930d90002d6e562727ae7d47 for the Recent material view.
It seems more appropriate to keep the whole date in the file tree view, though.

**Comment by CapacitorSet** [comment]
@robertolaru Agree, in general (so for notices and perhaps bookings too) it makes sense to use "time ago" in recent widgets and the whole date in full lists.
